### ISSUE TITLE
Error installing bllip-parser from environment.yml without gcc and gxx

### ISSUE THREAD

**Issue by MaxGhenis** [stanfordmlgroup/chexpert-labeler#20]
Per https://github.com/BLLIP/bllip-parser/issues/67, installing bllip-parser on Linux may require the GCC and GXX packages. I had the same error when loading the environment here. Adding this to `environment.yml` addressed it: 
```
  - gcc_linux-64
  - gxx_linux-64
```

**Comment by tinahuang222** [comment]
Adding  `gcc_linux-64 ` and `gxx_linux-64` to the environment*.yml is **not sufficient to solve the problem**. The bug still occurred, unable to `pip install bllipparser` because of `gcc` problem. 

That's because executable cannot reconcile codes using `gcc` and `g++` with installed packages `gcc_linux-64 ` and `gxx_linux-64` in this negbio* conda environment. To resolve that, you would have to manually add soft symbolic link within conda environment.

> ln -s /path/to/anaconda3/envs/negbio2.7/bin/x86_64-conda_cos6-linux-gnu-gcc /path/to/anaconda3/envs/negbio2.7/bin/gcc 
> ln -s /path/to/anaconda3/envs/negbio2.7/bin/x86_64-conda_cos6-linux-gnu-g++ /path/to/anaconda3/envs/negbio2.7/bin/g++

After properly linking the gcc and g++ executables, continue to update the conda environment.
> source activate negbio2.7
> conda env update -f environment2.7.yml
